//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MirzaevLibrary.AppDataFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookTable()
        {
            this.TicketTable = new HashSet<TicketTable>();
            this.TicketTable1 = new HashSet<TicketTable>();
        }
    
        public int PersonalNumberBook { get; set; }
        public string NameBook { get; set; }
        public int InstanceBook { get; set; }
        public int pnPublishingHouse { get; set; }
        public System.DateTime DatePublishingBook { get; set; }
        public int QuantityPublishingBook { get; set; }
        public int pnCategory { get; set; }
        public int pnGo { get; set; }
        public int pnCash { get; set; }
        public int LikeBook { get; set; }
        public int DislikeBook { get; set; }
        public int pnAuthor { get; set; }
        public Nullable<int> pnImage { get; set; }
    
        public virtual AuthorsTable AuthorsTable { get; set; }
        public virtual CashTable CashTable { get; set; }
        public virtual CategoryTable CategoryTable { get; set; }
        public virtual GoTable GoTable { get; set; }
        public virtual ImagebookTable ImagebookTable { get; set; }
        public virtual PublishingHouseTable PublishingHouseTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketTable> TicketTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketTable> TicketTable1 { get; set; }
    }
}
