//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MirzaevLibrary.AppDataFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public int PersonalNumberUser { get; set; }
        public string SurnameUser { get; set; }
        public string NameUser { get; set; }
        public string MiddlenameUser { get; set; }
        public int pnTicketUser { get; set; }
        public string AddressUser { get; set; }
        public string PhoneUser { get; set; }
        public string LoginUser { get; set; }
        public string PasswordUser { get; set; }
        public int pnRoleUser { get; set; }
        public int pnImageUser { get; set; }
    
        public virtual ImageUserTable ImageUserTable { get; set; }
        public virtual RoleTable RoleTable { get; set; }
        public virtual TicketTable TicketTable { get; set; }
    }
}
