//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MirzaevLibrary.AppDataFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public int PersonalNumber_User { get; set; }
        public string Surname_User { get; set; }
        public string Name_User { get; set; }
        public string Middlename_User { get; set; }
        public int pnTicket_User { get; set; }
        public string Address_User { get; set; }
        public string Phone_User { get; set; }
        public string Login_User { get; set; }
        public string Password_User { get; set; }
        public int pnRole_User { get; set; }
        public int pnImage_User { get; set; }
    
        public virtual ImageUserTable ImageUserTable { get; set; }
        public virtual RoleTable RoleTable { get; set; }
        public virtual TicketTable TicketTable { get; set; }
    }
}
